In [ ]:
import os
import pandas as pd
from datasets import load_dataset
from tqdm import tqdm
tqdm.pandas()

# Retrieved from: https://amazon-reviews-2023.github.io/
# NOTE: Use 2023 dataset as it is larger, more descriptive, more granular and cleaner compared to
#       previous datasets.
dataset_name = "McAuley-Lab/Amazon-Reviews-2023"

# NOTE: There are 33 categories + Unknown. Software is a subset.
category = "Software"

c:\Users\user\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

### Load User Reviews

In [2]:
#######################################################################################################
# Data Fields for User Reviews
#######################################################################################################
#
# - rating (float)             -->   Rating of the product (from 1.0 to 5.0)
# - title (str)                -->   Title of the user review
# - text (str)                 -->   Text body of the user review
# - images (list)              -->   Images that users post after they have received the product
#                                    Each image has different sizes (small, medium, large), represented
#                                    by the small_image_url, medium_image_url, and large_image_url
#                                    respectively
# - asin (str)                 -->   ID of the product
# - parent_asin (str)          -->   Parent ID of the product. Note: Products with different colors,
#                                    styles, sizes usually belong to the same parent ID. The “asin”
#                                    in previous Amazon datasets is actually parent ID. Please use
#                                    parent ID to find product meta
# - user_id (str)              -->   ID of the reviewer
# - timestamp (int)            -->   Time of the review (unix time)
# - verified_purchase (bool)   -->   User purchase verification
# - helpful_vote (int)         -->   Helpful votes of the review
#
#######################################################################################################

review_dataset = load_dataset(dataset_name, f"raw_review_{category}", trust_remote_code=True)

all_reviews = [review for review in tqdm(review_dataset["full"])]
review_df = pd.DataFrame(all_reviews)

review_df

100%|██████████| 4880181/4880181 [07:47<00:00, 10439.42it/s]

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1.0,malware,mcaffee IS malware,[],B07BFS3G7P,B0BQSK9QCF,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,1562182632076,0,False
1,5.0,Lots of Fun,I love playing tapped out because it is fun to...,[],B00CTQ6SIG,B00CTQ6SIG,AHSPLDNW5OOUK2PLH7GXLACFBZNQ,1424120336000,0,True
2,5.0,Light Up The Dark,I love this flashlight app! It really illumin...,[],B0066WJLU6,B0066WJLU6,AHSPLDNW5OOUK2PLH7GXLACFBZNQ,1362399267000,0,True
3,4.0,Fun game,One of my favorite games,[],B00KCYMAWK,B00KCYMAWK,AH6CATODIVPVUOJEWHRSRCSKAOHA,1561061428662,0,True
4,4.0,I am not that good at it but my kids are,Cute game. I am not that good at it but my kid...,[],B00P1RK566,B00P1RK566,AEINY4XOINMMJCK5GZ3M6MMHBN6A,1418257196000,0,True
...,...,...,...,...,...,...,...,...,...,...
4880176,5.0,Gog,Very fun and addictive and exciting,[],B0763N3MVW,B0763N3MVW,AGOKECUMAI3W6MC7A7KBFBJVPN7Q,1608919468753,0,True
4880177,1.0,WORST GAME EVER,WORST GAME EVER TOXIC PEOPLE AND BAD CONNECTIO...,[],B00ET56Y48,B00ET56Y48,AH6AMUNDOSZ2SGDIDMYSRE4RNMDQ,1609973647689,1,True
4880178,5.0,better!!!,This fabulous game is 10000 times better than ...,[],B009ZKSPDK,B009ZKSPDK,AH4PJ73QN75AJM5VSCT53AOADCGA,1369722216000,2,True
4880179,5.0,It Has Everything I Need And More,Awesome! I upgraded from CorelDraw 8. I was wo...,[],B00M9J3IOA,B00M9J3IOA,AHQETDYKHVDNGMGBWVJL6VJXJGFQ,1472923291000,0,True
4880180,5.0,Huge fan,Omg so fun it keeps me playing btw let's go ga...,[],B01I5OMSKM,B01I5OMSKM,AH22767FROBCSHB4Y3M4O37QETIQ,1563133201259,0,True

### Load Item Metadata

In [ ]:
#######################################################################################################
# Data Fields for Item Metadata
#######################################################################################################
#
# - main_category (str)	       -->   Main category (i.e., domain) of the product
# - title (str)	               -->   Name of the product
# - average_rating (float)     -->   Rating of the product shown on the product page
# - rating_number (int)        -->   Number of ratings in the product
# - features (list)            -->   Bullet-point format features of the product
# - description (list)         -->   Description of the product
# - price (float)              -->   Price in US dollars (at time of crawling)
# - images (list)              -->   Images of the product. Each image has different sizes (thumb, large,
#                                    hi_res). The “variant” field shows the position of image
# - videos (list)              -->   Videos of the product including title and url
# - store (str)	               -->   Store name of the product
# - categories (list)	       -->   Hierarchical categories of the product
# - details (dict)             -->   Product details, including materials, brand, sizes, etc
# - parent_asin (str)	       -->   Parent ID of the product
# - bought_together (list)     -->   Recommended bundles from the websites
#
#######################################################################################################

meta_dataset = load_dataset(dataset_name,f"raw_meta_{category}", split="full", trust_remote_code=True)

meta_df = pd.DataFrame(meta_dataset)

meta_df

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Appstore for Android,Accupressure Guide,3.6,NaN,[All the pressing point has been explained wit...,[Acupressure technique is very ancient and ver...,0.0,"{'hi_res': [None, None, None, None], 'large': ...","{'title': [''], 'url': [''], 'user_id': ['']}",mAppsguru,[],"{""Release Date"": ""2015"", ""Date first listed on...",B00VRPSGEO,None,None,None
1,Appstore for Android,Ankylosaurus Fights Back - Smithsonian's Prehi...,4.0,NaN,[ENCOURAGE literacy skills with highlighted na...,[Join Ankylosaurus in this interactive book ap...,2.99,"{'hi_res': [None, None, None, None, None], 'la...","{'title': [''], 'url': [''], 'user_id': ['']}","Oceanhouse Media, Inc",[],"{""Release Date"": ""2014"", ""Date first listed on...",B00NWQXXHQ,None,None,None
2,Appstore for Android,Mahjong 2015,3.1,NaN,[Mahjong 2015 is a free solitaire matching gam...,[Mahjong 2015 is a free solitaire matching gam...,0.0,"{'hi_res': [None, None, None], 'large': ['http...","{'title': [''], 'url': [''], 'user_id': ['']}",sophiathach,[],"{""Release Date"": ""2014"", ""Date first listed on...",B00RFKP6AC,None,None,None
3,Appstore for Android,Jewels Brick Breakout,4.2,NaN,"[Game Features:, - Intuitive touch controls wi...",[Jewels Brick Breakout is a glowing jewels bri...,0.0,"{'hi_res': [None, None, None, None, None, None...","{'title': [''], 'url': [''], 'user_id': ['']}",Bad Chicken,[],"{""Release Date"": ""2015"", ""Date first listed on...",B00SP2QU0E,None,None,None
4,Appstore for Android,Traffic Police: Off-Road Cub,3.3,NaN,"[In this game you will find:, - Killer police ...",[Become the best road police officer in Cube C...,0.0,"{'hi_res': [None, None, None, None], 'large': ...","{'title': [''], 'url': [''], 'user_id': ['']}",Dast 2 For Metro,[],"{""Release Date"": ""2016"", ""Date first listed on...",B01DZIT64O,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89246,Software,How to Start a Commercial Loan Broker Plus Bus...,3.2,2.0,[Everything You Need to Know About Starting a ...,[The How to Start a Commercial Loan Brokerage ...,29.95,"{'hi_res': [None, None, None, None, None], 'la...","{'title': [], 'url': [], 'user_id': []}",HowToStartABusinessDB,"[Software, Business & Office, Business & Marke...","{""Is Discontinued By Manufacturer"": ""No"", ""Ite...",B006KWVRGI,None,None,None
89247,Software,Norton Uninstall Deluxe,3.7,2.0,[Safely removes programs and files you no long...,[The safe uninstaller from the makers of Norto...,None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Symantec,"[Software, Utilities]","{""Is Discontinued By Manufacturer"": ""No"", ""Pac...",B000J54PRA,None,None,None
89248,None,Beginning Pro Tools LE 8 [Instant Access],3.0,3.0,[],[This video takes you from start to finish on ...,15.95,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Alfred Music,"[Software, Education & Reference]","{""Language"": ""English"", ""Item model number"": ""...",B00MG0OHB0,None,None,None
89249,None,Tell Me More Spanish Performance Version 9 (2 ...,1.5,2.0,[Spanish language-learning software with 2 lev...,"[From the Manufacturer, This award-winning lan...",209.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Auralog,"[Software, Education & Reference, Languages]","{""Language"": ""English, French"", ""Package Dimen...",B001GN6YUK,None,None,None
89250,Software,"Veryfi - receipts & bills tracker, expense rep...",4.3,6.0,[Automated — Veryfi removes the hassle of manu...,[Veryfi is a bookkeeper in your pocket. Ideal ...,None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Veryfi,"[Software, Accounting & Finance, Business Acco...","{""Date First Available"": ""August 22, 2017"", ""M...",B0751Q59HC,None,None,None

### Export Dataset

In [5]:
output_dir = "./output"

# Create output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Export DataFrame
review_df.to_parquet(f"{output_dir}/review_data.parquet", index=False)
meta_df.to_parquet(f"{output_dir}/meta_data.parquet", index=False)